//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	unsafe "unsafe"

	v1 "k8s.io/api/authorization/v1"
	authorizationv1beta1 "k8s.io/api/authorization/v1beta1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*authorizationv1beta1.LocalSubjectAccessReview)(nil), (*v1.LocalSubjectAccessReview)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_LocalSubjectAccessReview_To_v1_LocalSubjectAccessReview(a.(*authorizationv1beta1.LocalSubjectAccessReview), b.(*v1.LocalSubjectAccessReview), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.LocalSubjectAccessReview)(nil), (*authorizationv1beta1.LocalSubjectAccessReview)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_LocalSubjectAccessReview_To_v1beta1_LocalSubjectAccessReview(a.(*v1.LocalSubjectAccessReview), b.(*authorizationv1beta1.LocalSubjectAccessReview), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorizationv1beta1.NonResourceAttributes)(nil), (*v1.NonResourceAttributes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NonResourceAttributes_To_v1_NonResourceAttributes(a.(*authorizationv1beta1.NonResourceAttributes), b.(*v1.NonResourceAttributes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.NonResourceAttributes)(nil), (*authorizationv1beta1.NonResourceAttributes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_NonResourceAttributes_To_v1beta1_NonResourceAttributes(a.(*v1.NonResourceAttributes), b.(*authorizationv1beta1.NonResourceAttributes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorizationv1beta1.NonResourceRule)(nil), (*v1.NonResourceRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_NonResourceRule_To_v1_NonResourceRule(a.(*authorizationv1beta1.NonResourceRule), b.(*v1.NonResourceRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.NonResourceRule)(nil), (*authorizationv1beta1.NonResourceRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_NonResourceRule_To_v1beta1_NonResourceRule(a.(*v1.NonResourceRule), b.(*authorizationv1beta1.NonResourceRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorizationv1beta1.ResourceAttributes)(nil), (*v1.ResourceAttributes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ResourceAttributes_To_v1_ResourceAttributes(a.(*authorizationv1beta1.ResourceAttributes), b.(*v1.ResourceAttributes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.ResourceAttributes)(nil), (*authorizationv1beta1.ResourceAttributes)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ResourceAttributes_To_v1beta1_ResourceAttributes(a.(*v1.ResourceAttributes), b.(*authorizationv1beta1.ResourceAttributes), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorizationv1beta1.ResourceRule)(nil), (*v1.ResourceRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_ResourceRule_To_v1_ResourceRule(a.(*authorizationv1beta1.ResourceRule), b.(*v1.ResourceRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.ResourceRule)(nil), (*authorizationv1beta1.ResourceRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ResourceRule_To_v1beta1_ResourceRule(a.(*v1.ResourceRule), b.(*authorizationv1beta1.ResourceRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorizationv1beta1.SelfSubjectAccessReview)(nil), (*v1.SelfSubjectAccessReview)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SelfSubjectAccessReview_To_v1_SelfSubjectAccessReview(a.(*authorizationv1beta1.SelfSubjectAccessReview), b.(*v1.SelfSubjectAccessReview), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.SelfSubjectAccessReview)(nil), (*authorizationv1beta1.SelfSubjectAccessReview)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SelfSubjectAccessReview_To_v1beta1_SelfSubjectAccessReview(a.(*v1.SelfSubjectAccessReview), b.(*authorizationv1beta1.SelfSubjectAccessReview), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorizationv1beta1.SelfSubjectAccessReviewSpec)(nil), (*v1.SelfSubjectAccessReviewSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SelfSubjectAccessReviewSpec_To_v1_SelfSubjectAccessReviewSpec(a.(*authorizationv1beta1.SelfSubjectAccessReviewSpec), b.(*v1.SelfSubjectAccessReviewSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.SelfSubjectAccessReviewSpec)(nil), (*authorizationv1beta1.SelfSubjectAccessReviewSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SelfSubjectAccessReviewSpec_To_v1beta1_SelfSubjectAccessReviewSpec(a.(*v1.SelfSubjectAccessReviewSpec), b.(*authorizationv1beta1.SelfSubjectAccessReviewSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorizationv1beta1.SelfSubjectRulesReview)(nil), (*v1.SelfSubjectRulesReview)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SelfSubjectRulesReview_To_v1_SelfSubjectRulesReview(a.(*authorizationv1beta1.SelfSubjectRulesReview), b.(*v1.SelfSubjectRulesReview), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.SelfSubjectRulesReview)(nil), (*authorizationv1beta1.SelfSubjectRulesReview)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SelfSubjectRulesReview_To_v1beta1_SelfSubjectRulesReview(a.(*v1.SelfSubjectRulesReview), b.(*authorizationv1beta1.SelfSubjectRulesReview), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorizationv1beta1.SelfSubjectRulesReviewSpec)(nil), (*v1.SelfSubjectRulesReviewSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SelfSubjectRulesReviewSpec_To_v1_SelfSubjectRulesReviewSpec(a.(*authorizationv1beta1.SelfSubjectRulesReviewSpec), b.(*v1.SelfSubjectRulesReviewSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.SelfSubjectRulesReviewSpec)(nil), (*authorizationv1beta1.SelfSubjectRulesReviewSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SelfSubjectRulesReviewSpec_To_v1beta1_SelfSubjectRulesReviewSpec(a.(*v1.SelfSubjectRulesReviewSpec), b.(*authorizationv1beta1.SelfSubjectRulesReviewSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorizationv1beta1.SubjectAccessReview)(nil), (*v1.SubjectAccessReview)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SubjectAccessReview_To_v1_SubjectAccessReview(a.(*authorizationv1beta1.SubjectAccessReview), b.(*v1.SubjectAccessReview), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.SubjectAccessReview)(nil), (*authorizationv1beta1.SubjectAccessReview)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SubjectAccessReview_To_v1beta1_SubjectAccessReview(a.(*v1.SubjectAccessReview), b.(*authorizationv1beta1.SubjectAccessReview), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorizationv1beta1.SubjectAccessReviewSpec)(nil), (*v1.SubjectAccessReviewSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SubjectAccessReviewSpec_To_v1_SubjectAccessReviewSpec(a.(*authorizationv1beta1.SubjectAccessReviewSpec), b.(*v1.SubjectAccessReviewSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.SubjectAccessReviewSpec)(nil), (*authorizationv1beta1.SubjectAccessReviewSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SubjectAccessReviewSpec_To_v1beta1_SubjectAccessReviewSpec(a.(*v1.SubjectAccessReviewSpec), b.(*authorizationv1beta1.SubjectAccessReviewSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorizationv1beta1.SubjectAccessReviewStatus)(nil), (*v1.SubjectAccessReviewStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SubjectAccessReviewStatus_To_v1_SubjectAccessReviewStatus(a.(*authorizationv1beta1.SubjectAccessReviewStatus), b.(*v1.SubjectAccessReviewStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.SubjectAccessReviewStatus)(nil), (*authorizationv1beta1.SubjectAccessReviewStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SubjectAccessReviewStatus_To_v1beta1_SubjectAccessReviewStatus(a.(*v1.SubjectAccessReviewStatus), b.(*authorizationv1beta1.SubjectAccessReviewStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorizationv1beta1.SubjectRulesReviewStatus)(nil), (*v1.SubjectRulesReviewStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SubjectRulesReviewStatus_To_v1_SubjectRulesReviewStatus(a.(*authorizationv1beta1.SubjectRulesReviewStatus), b.(*v1.SubjectRulesReviewStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*v1.SubjectRulesReviewStatus)(nil), (*authorizationv1beta1.SubjectRulesReviewStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_SubjectRulesReviewStatus_To_v1beta1_SubjectRulesReviewStatus(a.(*v1.SubjectRulesReviewStatus), b.(*authorizationv1beta1.SubjectRulesReviewStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_LocalSubjectAccessReview_To_v1_LocalSubjectAccessReview(in *authorizationv1beta1.LocalSubjectAccessReview, out *v1.LocalSubjectAccessReview, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_SubjectAccessReviewSpec_To_v1_SubjectAccessReviewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_SubjectAccessReviewStatus_To_v1_SubjectAccessReviewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_LocalSubjectAccessReview_To_v1_LocalSubjectAccessReview is an autogenerated conversion function.
func Convert_v1beta1_LocalSubjectAccessReview_To_v1_LocalSubjectAccessReview(in *authorizationv1beta1.LocalSubjectAccessReview, out *v1.LocalSubjectAccessReview, s conversion.Scope) error {
	return autoConvert_v1beta1_LocalSubjectAccessReview_To_v1_LocalSubjectAccessReview(in, out, s)
}

func autoConvert_v1_LocalSubjectAccessReview_To_v1beta1_LocalSubjectAccessReview(in *v1.LocalSubjectAccessReview, out *authorizationv1beta1.LocalSubjectAccessReview, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_SubjectAccessReviewSpec_To_v1beta1_SubjectAccessReviewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_SubjectAccessReviewStatus_To_v1beta1_SubjectAccessReviewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_LocalSubjectAccessReview_To_v1beta1_LocalSubjectAccessReview is an autogenerated conversion function.
func Convert_v1_LocalSubjectAccessReview_To_v1beta1_LocalSubjectAccessReview(in *v1.LocalSubjectAccessReview, out *authorizationv1beta1.LocalSubjectAccessReview, s conversion.Scope) error {
	return autoConvert_v1_LocalSubjectAccessReview_To_v1beta1_LocalSubjectAccessReview(in, out, s)
}

func autoConvert_v1beta1_NonResourceAttributes_To_v1_NonResourceAttributes(in *authorizationv1beta1.NonResourceAttributes, out *v1.NonResourceAttributes, s conversion.Scope) error {
	*out = *(*v1.NonResourceAttributes)(unsafe.Pointer(in))
	return nil
}

// Convert_v1beta1_NonResourceAttributes_To_v1_NonResourceAttributes is an autogenerated conversion function.
func Convert_v1beta1_NonResourceAttributes_To_v1_NonResourceAttributes(in *authorizationv1beta1.NonResourceAttributes, out *v1.NonResourceAttributes, s conversion.Scope) error {
	return autoConvert_v1beta1_NonResourceAttributes_To_v1_NonResourceAttributes(in, out, s)
}

func autoConvert_v1_NonResourceAttributes_To_v1beta1_NonResourceAttributes(in *v1.NonResourceAttributes, out *authorizationv1beta1.NonResourceAttributes, s conversion.Scope) error {
	*out = *(*authorizationv1beta1.NonResourceAttributes)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_NonResourceAttributes_To_v1beta1_NonResourceAttributes is an autogenerated conversion function.
func Convert_v1_NonResourceAttributes_To_v1beta1_NonResourceAttributes(in *v1.NonResourceAttributes, out *authorizationv1beta1.NonResourceAttributes, s conversion.Scope) error {
	return autoConvert_v1_NonResourceAttributes_To_v1beta1_NonResourceAttributes(in, out, s)
}

func autoConvert_v1beta1_NonResourceRule_To_v1_NonResourceRule(in *authorizationv1beta1.NonResourceRule, out *v1.NonResourceRule, s conversion.Scope) error {
	*out = *(*v1.NonResourceRule)(unsafe.Pointer(in))
	return nil
}

// Convert_v1beta1_NonResourceRule_To_v1_NonResourceRule is an autogenerated conversion function.
func Convert_v1beta1_NonResourceRule_To_v1_NonResourceRule(in *authorizationv1beta1.NonResourceRule, out *v1.NonResourceRule, s conversion.Scope) error {
	return autoConvert_v1beta1_NonResourceRule_To_v1_NonResourceRule(in, out, s)
}

func autoConvert_v1_NonResourceRule_To_v1beta1_NonResourceRule(in *v1.NonResourceRule, out *authorizationv1beta1.NonResourceRule, s conversion.Scope) error {
	*out = *(*authorizationv1beta1.NonResourceRule)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_NonResourceRule_To_v1beta1_NonResourceRule is an autogenerated conversion function.
func Convert_v1_NonResourceRule_To_v1beta1_NonResourceRule(in *v1.NonResourceRule, out *authorizationv1beta1.NonResourceRule, s conversion.Scope) error {
	return autoConvert_v1_NonResourceRule_To_v1beta1_NonResourceRule(in, out, s)
}

func autoConvert_v1beta1_ResourceAttributes_To_v1_ResourceAttributes(in *authorizationv1beta1.ResourceAttributes, out *v1.ResourceAttributes, s conversion.Scope) error {
	*out = *(*v1.ResourceAttributes)(unsafe.Pointer(in))
	return nil
}

// Convert_v1beta1_ResourceAttributes_To_v1_ResourceAttributes is an autogenerated conversion function.
func Convert_v1beta1_ResourceAttributes_To_v1_ResourceAttributes(in *authorizationv1beta1.ResourceAttributes, out *v1.ResourceAttributes, s conversion.Scope) error {
	return autoConvert_v1beta1_ResourceAttributes_To_v1_ResourceAttributes(in, out, s)
}

func autoConvert_v1_ResourceAttributes_To_v1beta1_ResourceAttributes(in *v1.ResourceAttributes, out *authorizationv1beta1.ResourceAttributes, s conversion.Scope) error {
	*out = *(*authorizationv1beta1.ResourceAttributes)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_ResourceAttributes_To_v1beta1_ResourceAttributes is an autogenerated conversion function.
func Convert_v1_ResourceAttributes_To_v1beta1_ResourceAttributes(in *v1.ResourceAttributes, out *authorizationv1beta1.ResourceAttributes, s conversion.Scope) error {
	return autoConvert_v1_ResourceAttributes_To_v1beta1_ResourceAttributes(in, out, s)
}

func autoConvert_v1beta1_ResourceRule_To_v1_ResourceRule(in *authorizationv1beta1.ResourceRule, out *v1.ResourceRule, s conversion.Scope) error {
	*out = *(*v1.ResourceRule)(unsafe.Pointer(in))
	return nil
}

// Convert_v1beta1_ResourceRule_To_v1_ResourceRule is an autogenerated conversion function.
func Convert_v1beta1_ResourceRule_To_v1_ResourceRule(in *authorizationv1beta1.ResourceRule, out *v1.ResourceRule, s conversion.Scope) error {
	return autoConvert_v1beta1_ResourceRule_To_v1_ResourceRule(in, out, s)
}

func autoConvert_v1_ResourceRule_To_v1beta1_ResourceRule(in *v1.ResourceRule, out *authorizationv1beta1.ResourceRule, s conversion.Scope) error {
	*out = *(*authorizationv1beta1.ResourceRule)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_ResourceRule_To_v1beta1_ResourceRule is an autogenerated conversion function.
func Convert_v1_ResourceRule_To_v1beta1_ResourceRule(in *v1.ResourceRule, out *authorizationv1beta1.ResourceRule, s conversion.Scope) error {
	return autoConvert_v1_ResourceRule_To_v1beta1_ResourceRule(in, out, s)
}

func autoConvert_v1beta1_SelfSubjectAccessReview_To_v1_SelfSubjectAccessReview(in *authorizationv1beta1.SelfSubjectAccessReview, out *v1.SelfSubjectAccessReview, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_SelfSubjectAccessReviewSpec_To_v1_SelfSubjectAccessReviewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_SubjectAccessReviewStatus_To_v1_SubjectAccessReviewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_SelfSubjectAccessReview_To_v1_SelfSubjectAccessReview is an autogenerated conversion function.
func Convert_v1beta1_SelfSubjectAccessReview_To_v1_SelfSubjectAccessReview(in *authorizationv1beta1.SelfSubjectAccessReview, out *v1.SelfSubjectAccessReview, s conversion.Scope) error {
	return autoConvert_v1beta1_SelfSubjectAccessReview_To_v1_SelfSubjectAccessReview(in, out, s)
}

func autoConvert_v1_SelfSubjectAccessReview_To_v1beta1_SelfSubjectAccessReview(in *v1.SelfSubjectAccessReview, out *authorizationv1beta1.SelfSubjectAccessReview, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_SelfSubjectAccessReviewSpec_To_v1beta1_SelfSubjectAccessReviewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_SubjectAccessReviewStatus_To_v1beta1_SubjectAccessReviewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_SelfSubjectAccessReview_To_v1beta1_SelfSubjectAccessReview is an autogenerated conversion function.
func Convert_v1_SelfSubjectAccessReview_To_v1beta1_SelfSubjectAccessReview(in *v1.SelfSubjectAccessReview, out *authorizationv1beta1.SelfSubjectAccessReview, s conversion.Scope) error {
	return autoConvert_v1_SelfSubjectAccessReview_To_v1beta1_SelfSubjectAccessReview(in, out, s)
}

func autoConvert_v1beta1_SelfSubjectAccessReviewSpec_To_v1_SelfSubjectAccessReviewSpec(in *authorizationv1beta1.SelfSubjectAccessReviewSpec, out *v1.SelfSubjectAccessReviewSpec, s conversion.Scope) error {
	*out = *(*v1.SelfSubjectAccessReviewSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1beta1_SelfSubjectAccessReviewSpec_To_v1_SelfSubjectAccessReviewSpec is an autogenerated conversion function.
func Convert_v1beta1_SelfSubjectAccessReviewSpec_To_v1_SelfSubjectAccessReviewSpec(in *authorizationv1beta1.SelfSubjectAccessReviewSpec, out *v1.SelfSubjectAccessReviewSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_SelfSubjectAccessReviewSpec_To_v1_SelfSubjectAccessReviewSpec(in, out, s)
}

func autoConvert_v1_SelfSubjectAccessReviewSpec_To_v1beta1_SelfSubjectAccessReviewSpec(in *v1.SelfSubjectAccessReviewSpec, out *authorizationv1beta1.SelfSubjectAccessReviewSpec, s conversion.Scope) error {
	*out = *(*authorizationv1beta1.SelfSubjectAccessReviewSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_SelfSubjectAccessReviewSpec_To_v1beta1_SelfSubjectAccessReviewSpec is an autogenerated conversion function.
func Convert_v1_SelfSubjectAccessReviewSpec_To_v1beta1_SelfSubjectAccessReviewSpec(in *v1.SelfSubjectAccessReviewSpec, out *authorizationv1beta1.SelfSubjectAccessReviewSpec, s conversion.Scope) error {
	return autoConvert_v1_SelfSubjectAccessReviewSpec_To_v1beta1_SelfSubjectAccessReviewSpec(in, out, s)
}

func autoConvert_v1beta1_SelfSubjectRulesReview_To_v1_SelfSubjectRulesReview(in *authorizationv1beta1.SelfSubjectRulesReview, out *v1.SelfSubjectRulesReview, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_SelfSubjectRulesReviewSpec_To_v1_SelfSubjectRulesReviewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_SubjectRulesReviewStatus_To_v1_SubjectRulesReviewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_SelfSubjectRulesReview_To_v1_SelfSubjectRulesReview is an autogenerated conversion function.
func Convert_v1beta1_SelfSubjectRulesReview_To_v1_SelfSubjectRulesReview(in *authorizationv1beta1.SelfSubjectRulesReview, out *v1.SelfSubjectRulesReview, s conversion.Scope) error {
	return autoConvert_v1beta1_SelfSubjectRulesReview_To_v1_SelfSubjectRulesReview(in, out, s)
}

func autoConvert_v1_SelfSubjectRulesReview_To_v1beta1_SelfSubjectRulesReview(in *v1.SelfSubjectRulesReview, out *authorizationv1beta1.SelfSubjectRulesReview, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_SelfSubjectRulesReviewSpec_To_v1beta1_SelfSubjectRulesReviewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_SubjectRulesReviewStatus_To_v1beta1_SubjectRulesReviewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_SelfSubjectRulesReview_To_v1beta1_SelfSubjectRulesReview is an autogenerated conversion function.
func Convert_v1_SelfSubjectRulesReview_To_v1beta1_SelfSubjectRulesReview(in *v1.SelfSubjectRulesReview, out *authorizationv1beta1.SelfSubjectRulesReview, s conversion.Scope) error {
	return autoConvert_v1_SelfSubjectRulesReview_To_v1beta1_SelfSubjectRulesReview(in, out, s)
}

func autoConvert_v1beta1_SelfSubjectRulesReviewSpec_To_v1_SelfSubjectRulesReviewSpec(in *authorizationv1beta1.SelfSubjectRulesReviewSpec, out *v1.SelfSubjectRulesReviewSpec, s conversion.Scope) error {
	*out = *(*v1.SelfSubjectRulesReviewSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1beta1_SelfSubjectRulesReviewSpec_To_v1_SelfSubjectRulesReviewSpec is an autogenerated conversion function.
func Convert_v1beta1_SelfSubjectRulesReviewSpec_To_v1_SelfSubjectRulesReviewSpec(in *authorizationv1beta1.SelfSubjectRulesReviewSpec, out *v1.SelfSubjectRulesReviewSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_SelfSubjectRulesReviewSpec_To_v1_SelfSubjectRulesReviewSpec(in, out, s)
}

func autoConvert_v1_SelfSubjectRulesReviewSpec_To_v1beta1_SelfSubjectRulesReviewSpec(in *v1.SelfSubjectRulesReviewSpec, out *authorizationv1beta1.SelfSubjectRulesReviewSpec, s conversion.Scope) error {
	*out = *(*authorizationv1beta1.SelfSubjectRulesReviewSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_SelfSubjectRulesReviewSpec_To_v1beta1_SelfSubjectRulesReviewSpec is an autogenerated conversion function.
func Convert_v1_SelfSubjectRulesReviewSpec_To_v1beta1_SelfSubjectRulesReviewSpec(in *v1.SelfSubjectRulesReviewSpec, out *authorizationv1beta1.SelfSubjectRulesReviewSpec, s conversion.Scope) error {
	return autoConvert_v1_SelfSubjectRulesReviewSpec_To_v1beta1_SelfSubjectRulesReviewSpec(in, out, s)
}

func autoConvert_v1beta1_SubjectAccessReview_To_v1_SubjectAccessReview(in *authorizationv1beta1.SubjectAccessReview, out *v1.SubjectAccessReview, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_SubjectAccessReviewSpec_To_v1_SubjectAccessReviewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_SubjectAccessReviewStatus_To_v1_SubjectAccessReviewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_SubjectAccessReview_To_v1_SubjectAccessReview is an autogenerated conversion function.
func Convert_v1beta1_SubjectAccessReview_To_v1_SubjectAccessReview(in *authorizationv1beta1.SubjectAccessReview, out *v1.SubjectAccessReview, s conversion.Scope) error {
	return autoConvert_v1beta1_SubjectAccessReview_To_v1_SubjectAccessReview(in, out, s)
}

func autoConvert_v1_SubjectAccessReview_To_v1beta1_SubjectAccessReview(in *v1.SubjectAccessReview, out *authorizationv1beta1.SubjectAccessReview, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_SubjectAccessReviewSpec_To_v1beta1_SubjectAccessReviewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_SubjectAccessReviewStatus_To_v1beta1_SubjectAccessReviewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_SubjectAccessReview_To_v1beta1_SubjectAccessReview is an autogenerated conversion function.
func Convert_v1_SubjectAccessReview_To_v1beta1_SubjectAccessReview(in *v1.SubjectAccessReview, out *authorizationv1beta1.SubjectAccessReview, s conversion.Scope) error {
	return autoConvert_v1_SubjectAccessReview_To_v1beta1_SubjectAccessReview(in, out, s)
}

func autoConvert_v1beta1_SubjectAccessReviewSpec_To_v1_SubjectAccessReviewSpec(in *authorizationv1beta1.SubjectAccessReviewSpec, out *v1.SubjectAccessReviewSpec, s conversion.Scope) error {
	*out = *(*v1.SubjectAccessReviewSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1beta1_SubjectAccessReviewSpec_To_v1_SubjectAccessReviewSpec is an autogenerated conversion function.
func Convert_v1beta1_SubjectAccessReviewSpec_To_v1_SubjectAccessReviewSpec(in *authorizationv1beta1.SubjectAccessReviewSpec, out *v1.SubjectAccessReviewSpec, s conversion.Scope) error {
	return autoConvert_v1beta1_SubjectAccessReviewSpec_To_v1_SubjectAccessReviewSpec(in, out, s)
}

func autoConvert_v1_SubjectAccessReviewSpec_To_v1beta1_SubjectAccessReviewSpec(in *v1.SubjectAccessReviewSpec, out *authorizationv1beta1.SubjectAccessReviewSpec, s conversion.Scope) error {
	*out = *(*authorizationv1beta1.SubjectAccessReviewSpec)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_SubjectAccessReviewSpec_To_v1beta1_SubjectAccessReviewSpec is an autogenerated conversion function.
func Convert_v1_SubjectAccessReviewSpec_To_v1beta1_SubjectAccessReviewSpec(in *v1.SubjectAccessReviewSpec, out *authorizationv1beta1.SubjectAccessReviewSpec, s conversion.Scope) error {
	return autoConvert_v1_SubjectAccessReviewSpec_To_v1beta1_SubjectAccessReviewSpec(in, out, s)
}

func autoConvert_v1beta1_SubjectAccessReviewStatus_To_v1_SubjectAccessReviewStatus(in *authorizationv1beta1.SubjectAccessReviewStatus, out *v1.SubjectAccessReviewStatus, s conversion.Scope) error {
	*out = *(*v1.SubjectAccessReviewStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1beta1_SubjectAccessReviewStatus_To_v1_SubjectAccessReviewStatus is an autogenerated conversion function.
func Convert_v1beta1_SubjectAccessReviewStatus_To_v1_SubjectAccessReviewStatus(in *authorizationv1beta1.SubjectAccessReviewStatus, out *v1.SubjectAccessReviewStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_SubjectAccessReviewStatus_To_v1_SubjectAccessReviewStatus(in, out, s)
}

func autoConvert_v1_SubjectAccessReviewStatus_To_v1beta1_SubjectAccessReviewStatus(in *v1.SubjectAccessReviewStatus, out *authorizationv1beta1.SubjectAccessReviewStatus, s conversion.Scope) error {
	*out = *(*authorizationv1beta1.SubjectAccessReviewStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_SubjectAccessReviewStatus_To_v1beta1_SubjectAccessReviewStatus is an autogenerated conversion function.
func Convert_v1_SubjectAccessReviewStatus_To_v1beta1_SubjectAccessReviewStatus(in *v1.SubjectAccessReviewStatus, out *authorizationv1beta1.SubjectAccessReviewStatus, s conversion.Scope) error {
	return autoConvert_v1_SubjectAccessReviewStatus_To_v1beta1_SubjectAccessReviewStatus(in, out, s)
}

func autoConvert_v1beta1_SubjectRulesReviewStatus_To_v1_SubjectRulesReviewStatus(in *authorizationv1beta1.SubjectRulesReviewStatus, out *v1.SubjectRulesReviewStatus, s conversion.Scope) error {
	*out = *(*v1.SubjectRulesReviewStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1beta1_SubjectRulesReviewStatus_To_v1_SubjectRulesReviewStatus is an autogenerated conversion function.
func Convert_v1beta1_SubjectRulesReviewStatus_To_v1_SubjectRulesReviewStatus(in *authorizationv1beta1.SubjectRulesReviewStatus, out *v1.SubjectRulesReviewStatus, s conversion.Scope) error {
	return autoConvert_v1beta1_SubjectRulesReviewStatus_To_v1_SubjectRulesReviewStatus(in, out, s)
}

func autoConvert_v1_SubjectRulesReviewStatus_To_v1beta1_SubjectRulesReviewStatus(in *v1.SubjectRulesReviewStatus, out *authorizationv1beta1.SubjectRulesReviewStatus, s conversion.Scope) error {
	*out = *(*authorizationv1beta1.SubjectRulesReviewStatus)(unsafe.Pointer(in))
	return nil
}

// Convert_v1_SubjectRulesReviewStatus_To_v1beta1_SubjectRulesReviewStatus is an autogenerated conversion function.
func Convert_v1_SubjectRulesReviewStatus_To_v1beta1_SubjectRulesReviewStatus(in *v1.SubjectRulesReviewStatus, out *authorizationv1beta1.SubjectRulesReviewStatus, s conversion.Scope) error {
	return autoConvert_v1_SubjectRulesReviewStatus_To_v1beta1_SubjectRulesReviewStatus(in, out, s)
}
