//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	admissionv1 "k8s.io/api/admission/v1"
	authorizationv1 "k8s.io/api/authorization/v1"
	authorizationv1alpha1 "k8s.io/api/authorization/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	types "k8s.io/apimachinery/pkg/types"
	admission "k8s.io/kubernetes/pkg/apis/admission"
	authenticationv1 "k8s.io/kubernetes/pkg/apis/authentication/v1"
	authorization "k8s.io/kubernetes/pkg/apis/authorization"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*authorizationv1alpha1.AuthorizationConditionsRequest)(nil), (*authorization.AuthorizationConditionsRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuthorizationConditionsRequest_To_authorization_AuthorizationConditionsRequest(a.(*authorizationv1alpha1.AuthorizationConditionsRequest), b.(*authorization.AuthorizationConditionsRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorization.AuthorizationConditionsRequest)(nil), (*authorizationv1alpha1.AuthorizationConditionsRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authorization_AuthorizationConditionsRequest_To_v1alpha1_AuthorizationConditionsRequest(a.(*authorization.AuthorizationConditionsRequest), b.(*authorizationv1alpha1.AuthorizationConditionsRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorizationv1alpha1.AuthorizationConditionsResponse)(nil), (*authorization.AuthorizationConditionsResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuthorizationConditionsResponse_To_authorization_AuthorizationConditionsResponse(a.(*authorizationv1alpha1.AuthorizationConditionsResponse), b.(*authorization.AuthorizationConditionsResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorization.AuthorizationConditionsResponse)(nil), (*authorizationv1alpha1.AuthorizationConditionsResponse)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authorization_AuthorizationConditionsResponse_To_v1alpha1_AuthorizationConditionsResponse(a.(*authorization.AuthorizationConditionsResponse), b.(*authorizationv1alpha1.AuthorizationConditionsResponse), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorizationv1alpha1.AuthorizationConditionsReview)(nil), (*authorization.AuthorizationConditionsReview)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_AuthorizationConditionsReview_To_authorization_AuthorizationConditionsReview(a.(*authorizationv1alpha1.AuthorizationConditionsReview), b.(*authorization.AuthorizationConditionsReview), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*authorization.AuthorizationConditionsReview)(nil), (*authorizationv1alpha1.AuthorizationConditionsReview)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_authorization_AuthorizationConditionsReview_To_v1alpha1_AuthorizationConditionsReview(a.(*authorization.AuthorizationConditionsReview), b.(*authorizationv1alpha1.AuthorizationConditionsReview), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_AuthorizationConditionsRequest_To_authorization_AuthorizationConditionsRequest(in *authorizationv1alpha1.AuthorizationConditionsRequest, out *authorization.AuthorizationConditionsRequest, s conversion.Scope) error {
	out.UID = types.UID(in.UID)
	out.Kind = in.Kind
	out.Resource = in.Resource
	out.SubResource = in.SubResource
	out.RequestKind = (*v1.GroupVersionKind)(unsafe.Pointer(in.RequestKind))
	out.RequestResource = (*v1.GroupVersionResource)(unsafe.Pointer(in.RequestResource))
	out.RequestSubResource = in.RequestSubResource
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Operation = admission.Operation(in.Operation)
	out.AuthorizationVerb = in.AuthorizationVerb
	if err := authenticationv1.Convert_v1_UserInfo_To_authentication_UserInfo(&in.UserInfo, &out.UserInfo, s); err != nil {
		return err
	}
	out.Object = in.Object
	out.OldObject = in.OldObject
	out.DryRun = (*bool)(unsafe.Pointer(in.DryRun))
	out.Options = in.Options
	// FIXME: Provide conversion function to convert authorizationv1.SubjectAccessReviewConditionSet to authorization.SubjectAccessReviewConditionSet
	compileErrorOnMissingConversion()
	return nil
}

// Convert_v1alpha1_AuthorizationConditionsRequest_To_authorization_AuthorizationConditionsRequest is an autogenerated conversion function.
func Convert_v1alpha1_AuthorizationConditionsRequest_To_authorization_AuthorizationConditionsRequest(in *authorizationv1alpha1.AuthorizationConditionsRequest, out *authorization.AuthorizationConditionsRequest, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthorizationConditionsRequest_To_authorization_AuthorizationConditionsRequest(in, out, s)
}

func autoConvert_authorization_AuthorizationConditionsRequest_To_v1alpha1_AuthorizationConditionsRequest(in *authorization.AuthorizationConditionsRequest, out *authorizationv1alpha1.AuthorizationConditionsRequest, s conversion.Scope) error {
	out.UID = types.UID(in.UID)
	out.Kind = in.Kind
	out.Resource = in.Resource
	out.SubResource = in.SubResource
	out.RequestKind = (*v1.GroupVersionKind)(unsafe.Pointer(in.RequestKind))
	out.RequestResource = (*v1.GroupVersionResource)(unsafe.Pointer(in.RequestResource))
	out.RequestSubResource = in.RequestSubResource
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Operation = admissionv1.Operation(in.Operation)
	out.AuthorizationVerb = in.AuthorizationVerb
	if err := authenticationv1.Convert_authentication_UserInfo_To_v1_UserInfo(&in.UserInfo, &out.UserInfo, s); err != nil {
		return err
	}
	out.Object = in.Object
	out.OldObject = in.OldObject
	out.DryRun = (*bool)(unsafe.Pointer(in.DryRun))
	out.Options = in.Options
	// FIXME: Provide conversion function to convert authorization.SubjectAccessReviewConditionSet to authorizationv1.SubjectAccessReviewConditionSet
	compileErrorOnMissingConversion()
	return nil
}

// Convert_authorization_AuthorizationConditionsRequest_To_v1alpha1_AuthorizationConditionsRequest is an autogenerated conversion function.
func Convert_authorization_AuthorizationConditionsRequest_To_v1alpha1_AuthorizationConditionsRequest(in *authorization.AuthorizationConditionsRequest, out *authorizationv1alpha1.AuthorizationConditionsRequest, s conversion.Scope) error {
	return autoConvert_authorization_AuthorizationConditionsRequest_To_v1alpha1_AuthorizationConditionsRequest(in, out, s)
}

func autoConvert_v1alpha1_AuthorizationConditionsResponse_To_authorization_AuthorizationConditionsResponse(in *authorizationv1alpha1.AuthorizationConditionsResponse, out *authorization.AuthorizationConditionsResponse, s conversion.Scope) error {
	out.UID = types.UID(in.UID)
	out.Allowed = in.Allowed
	out.Denied = in.Denied
	out.Result = (*v1.Status)(unsafe.Pointer(in.Result))
	out.AuditAnnotations = *(*map[string]string)(unsafe.Pointer(&in.AuditAnnotations))
	out.Warnings = *(*[]string)(unsafe.Pointer(&in.Warnings))
	return nil
}

// Convert_v1alpha1_AuthorizationConditionsResponse_To_authorization_AuthorizationConditionsResponse is an autogenerated conversion function.
func Convert_v1alpha1_AuthorizationConditionsResponse_To_authorization_AuthorizationConditionsResponse(in *authorizationv1alpha1.AuthorizationConditionsResponse, out *authorization.AuthorizationConditionsResponse, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthorizationConditionsResponse_To_authorization_AuthorizationConditionsResponse(in, out, s)
}

func autoConvert_authorization_AuthorizationConditionsResponse_To_v1alpha1_AuthorizationConditionsResponse(in *authorization.AuthorizationConditionsResponse, out *authorizationv1alpha1.AuthorizationConditionsResponse, s conversion.Scope) error {
	out.UID = types.UID(in.UID)
	out.Allowed = in.Allowed
	out.Denied = in.Denied
	out.Result = (*v1.Status)(unsafe.Pointer(in.Result))
	out.AuditAnnotations = *(*map[string]string)(unsafe.Pointer(&in.AuditAnnotations))
	out.Warnings = *(*[]string)(unsafe.Pointer(&in.Warnings))
	return nil
}

// Convert_authorization_AuthorizationConditionsResponse_To_v1alpha1_AuthorizationConditionsResponse is an autogenerated conversion function.
func Convert_authorization_AuthorizationConditionsResponse_To_v1alpha1_AuthorizationConditionsResponse(in *authorization.AuthorizationConditionsResponse, out *authorizationv1alpha1.AuthorizationConditionsResponse, s conversion.Scope) error {
	return autoConvert_authorization_AuthorizationConditionsResponse_To_v1alpha1_AuthorizationConditionsResponse(in, out, s)
}

func autoConvert_v1alpha1_AuthorizationConditionsReview_To_authorization_AuthorizationConditionsReview(in *authorizationv1alpha1.AuthorizationConditionsReview, out *authorization.AuthorizationConditionsReview, s conversion.Scope) error {
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(authorization.AuthorizationConditionsRequest)
		if err := Convert_v1alpha1_AuthorizationConditionsRequest_To_authorization_AuthorizationConditionsRequest(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Request = nil
	}
	out.Response = (*authorization.AuthorizationConditionsResponse)(unsafe.Pointer(in.Response))
	return nil
}

// Convert_v1alpha1_AuthorizationConditionsReview_To_authorization_AuthorizationConditionsReview is an autogenerated conversion function.
func Convert_v1alpha1_AuthorizationConditionsReview_To_authorization_AuthorizationConditionsReview(in *authorizationv1alpha1.AuthorizationConditionsReview, out *authorization.AuthorizationConditionsReview, s conversion.Scope) error {
	return autoConvert_v1alpha1_AuthorizationConditionsReview_To_authorization_AuthorizationConditionsReview(in, out, s)
}

func autoConvert_authorization_AuthorizationConditionsReview_To_v1alpha1_AuthorizationConditionsReview(in *authorization.AuthorizationConditionsReview, out *authorizationv1alpha1.AuthorizationConditionsReview, s conversion.Scope) error {
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(authorizationv1alpha1.AuthorizationConditionsRequest)
		if err := Convert_authorization_AuthorizationConditionsRequest_To_v1alpha1_AuthorizationConditionsRequest(*in, *out, s); err != nil {
			return err
		}
	} else {
		out.Request = nil
	}
	out.Response = (*authorizationv1alpha1.AuthorizationConditionsResponse)(unsafe.Pointer(in.Response))
	return nil
}

// Convert_authorization_AuthorizationConditionsReview_To_v1alpha1_AuthorizationConditionsReview is an autogenerated conversion function.
func Convert_authorization_AuthorizationConditionsReview_To_v1alpha1_AuthorizationConditionsReview(in *authorization.AuthorizationConditionsReview, out *authorizationv1alpha1.AuthorizationConditionsReview, s conversion.Scope) error {
	return autoConvert_authorization_AuthorizationConditionsReview_To_v1alpha1_AuthorizationConditionsReview(in, out, s)
}
