/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-codegen.sh

// AUTO-GENERATED FUNCTIONS START HERE. DO NOT EDIT.
var map_AuthorizationConditionsRequest = map[string]string{
	"": "AuthorizationConditionsRequest describes the authorization conditions request.",
}

func (AuthorizationConditionsRequest) SwaggerDoc() map[string]string {
	return map_AuthorizationConditionsRequest
}

var map_AuthorizationConditionsResponse = map[string]string{
	"": "AuthorizationConditionsResponse describes an authorization conditions response.",
}

func (AuthorizationConditionsResponse) SwaggerDoc() map[string]string {
	return map_AuthorizationConditionsResponse
}

var map_AuthorizationConditionsReview = map[string]string{
	"":         "AuthorizationConditionsReview describes a request to evaluate authorization conditions.",
	"metadata": "metadata is the standard list metadata. In AuthorizationConditionsReview, it must be an empty struct. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata",
	"request":  "Request describes the attributes for the authorization conditions request.",
	"response": "Response describes the attributes for the authorization conditions response.",
}

func (AuthorizationConditionsReview) SwaggerDoc() map[string]string {
	return map_AuthorizationConditionsReview
}

var map_AuthorizationConditionsTargetAdmissionControl = map[string]string{
	"operation": "Name is the name of the object as presented in the request.  On a CREATE operation, the client may omit name and rely on the server to generate the name.  If that is the case, this field will contain an empty string. Name string `json:\"name,omitempty\" protobuf:\"bytes,5,opt,name=name\"` Namespace is the namespace associated with the request (if any). Namespace string `json:\"namespace,omitempty\" protobuf:\"bytes,6,opt,name=namespace\"` Operation is the operation being performed. This may be different than the operation requested. e.g. a patch can result in either a CREATE or UPDATE Operation.",
	"object":    "UserInfo is information about the requesting user UserInfo authenticationv1.UserInfo `json:\"userInfo\" protobuf:\"bytes,9,opt,name=userInfo\"` Object is the object from the incoming request.",
	"oldObject": "OldObject is the existing object. Only populated for DELETE and UPDATE requests.",
	"dryRun":    "DryRun indicates that modifications will definitely not be persisted for this request. Defaults to false.",
	"options":   "Options is the operation option structure of the operation being performed. e.g. `meta.k8s.io/v1.DeleteOptions` or `meta.k8s.io/v1.CreateOptions`. This may be different than the options the caller provided. e.g. for a patch request the performed Operation might be a CREATE, in which case the Options will a `meta.k8s.io/v1.CreateOptions` even though the caller provided `meta.k8s.io/v1.PatchOptions`.",
}

func (AuthorizationConditionsTargetAdmissionControl) SwaggerDoc() map[string]string {
	return map_AuthorizationConditionsTargetAdmissionControl
}

var map_Condition = map[string]string{
	"":            "Condition represents a single authorization condition to be evaluated against data available later in the request chain, e.g. objects available in admission.",
	"id":          "id uniquely identifies this condition within the scope of the authorizer that authored it. Validated as a Kubernetes label key.",
	"effect":      "effect specifies how the condition evaluating to \"true\" should be treated.",
	"condition":   "condition is an opaque string that represents the condition to be evaluated. It is a pure, deterministic function from condition data to a boolean.",
	"description": "description is an optional human-friendly description that can be shown as an error message or for debugging.",
}

func (Condition) SwaggerDoc() map[string]string {
	return map_Condition
}

var map_ConditionsAwareDecision = map[string]string{
	"":                "ConditionsAwareDecision represents one authorizer's decision. It is an enum type, with variants described in ConditionsAwareDecisionType, plus a reason and error.",
	"type":            "type describes the type of the decision, and acts as an enum discriminator.",
	"reason":          "reason is optional. It indicates why a request was allowed or denied.",
	"evaluationError": "evaluationError is an indication that some error occurred during the authorization check. It is entirely possible to get an error and be able to continue determine authorization status in spite of it. For instance, RBAC can be missing a role, but enough roles are still present and bound to reason about the request.",
	"conditionsMap":   "conditionsMap represents a conditional decision, modelled as a map of conditions. Must be non-null when type == \"ConditionsMap\", otherwise this field must be unset.",
	"union":           "union forms an ordered tree of decisions, where the union decision is represented by an internal node, and all other decision types are leaf nodes. During evaluation, the leaf decisions are evaluated in depth-first order, until an Allow or Deny decision is found. The order of the decisions must match exactly the order of the authorizers in the union authorizer. At least one of the leaves must be of type ConditionsMap, as otherwise the union could be trivially reduced to just a single Allow/Deny/NoOpinion.\n\nMust have at least one element when type == \"Union\", otherwise this field must be unset.",
}

func (ConditionsAwareDecision) SwaggerDoc() map[string]string {
	return map_ConditionsAwareDecision
}

var map_ConditionsMap = map[string]string{
	"":                 "ConditionsMap represents a map of conditions.",
	"conditionsTarget": "conditionsTarget describes the target data the conditions are written against.",
	"conditionsType":   "conditionsType describes the type (format/encoding/language) of all conditions in the map.",
	"conditions":       "conditions is an unordered map of conditions, keyed by ID, that should be evaluated against the specified, to determine whether the authorizer that authored the conditions allows the request. If any ConditionsEffect=Deny condition evaluates to true or errors, the evaluated decision must be Deny. Else if any ConditionsEffect=NoOpinion condition evaluates to true or errors, the evaluated decision must be NoOpinion. Else if any ConditionsEffect=Allow condition evaluates to true, the evaluated decision must be Allow. Else, the evaluated decision must be NoOpinion.",
}

func (ConditionsMap) SwaggerDoc() map[string]string {
	return map_ConditionsMap
}

// AUTO-GENERATED FUNCTIONS END HERE
